// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2GoIGSZEZ27mu9QtnU2lpTFMyt5EH5C8',
    appId: '1:1054382652000:web:6000e3b87ae4c557c2e105',
    messagingSenderId: '1054382652000',
    projectId: 'tiendavirtual-4ac4c',
    authDomain: 'tiendavirtual-4ac4c.firebaseapp.com',
    storageBucket: 'tiendavirtual-4ac4c.firebasestorage.app',
    measurementId: 'G-X92BDD723Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyFbVDz8y0gDs3exHXb-2HbJbXjXCpdhs',
    appId: '1:1054382652000:android:64e010660744a8eac2e105',
    messagingSenderId: '1054382652000',
    projectId: 'tiendavirtual-4ac4c',
    storageBucket: 'tiendavirtual-4ac4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGgrQ8WoyyEeSOS_ogPP-WF0iDNZGTdL8',
    appId: '1:1054382652000:ios:dc088accc1a6e22ac2e105',
    messagingSenderId: '1054382652000',
    projectId: 'tiendavirtual-4ac4c',
    storageBucket: 'tiendavirtual-4ac4c.firebasestorage.app',
    iosBundleId: 'com.example.appTienda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGgrQ8WoyyEeSOS_ogPP-WF0iDNZGTdL8',
    appId: '1:1054382652000:ios:dc088accc1a6e22ac2e105',
    messagingSenderId: '1054382652000',
    projectId: 'tiendavirtual-4ac4c',
    storageBucket: 'tiendavirtual-4ac4c.firebasestorage.app',
    iosBundleId: 'com.example.appTienda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2GoIGSZEZ27mu9QtnU2lpTFMyt5EH5C8',
    appId: '1:1054382652000:web:1e2c256010006338c2e105',
    messagingSenderId: '1054382652000',
    projectId: 'tiendavirtual-4ac4c',
    authDomain: 'tiendavirtual-4ac4c.firebaseapp.com',
    storageBucket: 'tiendavirtual-4ac4c.firebasestorage.app',
    measurementId: 'G-RRR7J97WT9',
  );
}
